<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-65CDRDN" failures="1" tests="1" name="com.test.salesforce2" time="0.497" errors="0" timestamp="31 Jan 2021 11:08:08 GMT">
  <testcase classname="com.base.salesforce.Baseclass" name="@AfterTest quitBrowser" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.base.salesforce.Baseclass.quitBrowser(Baseclass.java:51)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest quitBrowser -->
  <testcase classname="com.test.salesforce2.DeleteAcctTest" name="deleteTest" time="0.09">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.base.salesforce.Baseclass.launchBrowser(Baseclass.java:42)
at com.pages.salesforce.LoginPage.openUrl(LoginPage.java:14)
at com.pages.salesforce.HomePage.appLauncher(HomePage.java:11)
at com.pages.salesforce.DeleteAccount.deleteAccount(DeleteAccount.java:14)
at com.test.salesforce2.DeleteAcctTest.deleteTest(DeleteAcctTest.java:13)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- deleteTest -->
</testsuite> <!-- com.test.salesforce2 -->
